Repository danglotb/skillful_network, pull requests merged in 2020-07, with the labels that each got.

#38 ##-pf-feat-back-security-toggle V1.0
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/security/configuration/WebSecurity.java
  skillful_network_server/src/main/resources/application-dev.properties
  skillful_network_server/src/main/resources/application-prod.properties
  skillful_network_server/src/main/resources/application-test.properties
Labels: code, enhancement

#34 0(bd) refactor: autocompletion for perks
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/tools/AutoCompletion.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/tools/Candidate.java
  skillful_network_server/src/test/java/fr/uca/cdr/skillful_network/tools/AutoCompletionTest.java
Labels: code

#42 1.3.1-pf-feat-follow v1.1 build rest api for basic FST features :
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/user/FollowStateTrackerController.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/entities/user/FollowStateTracker.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/entities/user/Followable.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/entities/user/Follower.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/entities/user/Notification.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/entities/user/User.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/repositories/user/FollowStateTrackerRepository.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/repositories/user/NotificationRepository.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/impl/user/FollowStateTrackerServiceImpl.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/user/FollowStateTrackerService.java
Labels: back, code

#33 3 sh feat refonte password FIX #29
  skillful_network_client/src/app/app-routing.module.ts
  skillful_network_client/src/app/app.module.ts
  skillful_network_client/src/app/home/home.module.ts
  skillful_network_client/src/app/login/login.component.ts
  skillful_network_client/src/app/password-forgotten/password-forgotten.component.html
  skillful_network_client/src/app/password-forgotten/password-forgotten.component.scss
  skillful_network_client/src/app/password-forgotten/password-forgotten.component.ts
  skillful_network_client/src/app/registration-confirmation/registration-confirmation.component.html
  skillful_network_client/src/app/registration-confirmation/registration-confirmation.component.scss
  skillful_network_client/src/app/registration-confirmation/registration-confirmation.component.spec.ts
  skillful_network_client/src/app/registration-confirmation/registration-confirmation.component.ts
  skillful_network_client/src/app/shared/components/component.module.ts
  skillful_network_client/src/app/shared/components/login-view/login-view.component.html
  skillful_network_client/src/app/shared/components/login-view/login-view.component.scss
  skillful_network_client/src/app/shared/components/login-view/login-view.component.spec.ts
  skillful_network_client/src/app/shared/components/login-view/login-view.component.ts
  skillful_network_client/src/app/shared/services/role.service.ts
  skillful_network_client/src/app/shared/services/user.service.ts
  skillful_network_client/src/styles.scss
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/user/RoleController.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/user/UserController.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/entities/user/Role.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/entities/user/User.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/request/ConfirmationRegisterForm.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/AuthenticationService.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/impl/AuthenticationServiceImpl.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/impl/user/RoleServiceImpl.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/impl/user/UserServiceImpl.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/user/RoleService.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/user/UserService.java
  skillful_network_server/src/test/java/fr/uca/cdr/skillful_network/controllers/user/RoleControllerTest.java
  skillful_network_server/src/test/java/fr/uca/cdr/skillful_network/controllers/user/UserControllerTest.java
  skillful_network_server/src/test/java/fr/uca/cdr/skillful_network/entities/user/RoleTest.java
  skillful_network_server/src/test/java/fr/uca/cdr/skillful_network/services/user/UserServiceTest.java
Labels: code, enhancement

#48 1.3.1-pf-feat-follow v2.3 completed REST methods : status, notifiable
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/user/FollowStateTrackerController.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/repositories/user/FollowStateTrackerRepository.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/impl/user/FollowStateTrackerServiceImpl.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/user/FollowStateTrackerService.java
Labels: back, code

#56 1.3.1-pf-feat-follow v3.4 completed REST API for notifications and some add-ons
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/user/FollowStateTrackerController.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/entities/user/FollowStateTracker.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/entities/user/Follower.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/entities/user/Notification.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/entities/user/User.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/repositories/user/NotificationRepository.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/impl/user/FollowStateTrackerServiceImpl.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/user/FollowStateTrackerService.java
Labels: back, code

#59 1.3.1-pf-feat-follow v4.1 add some follower samples in followers.json
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/Application.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/entities/user/FollowStateTracker.java
  skillful_network_server/src/main/resources/data/followers.json
  skillful_network_server/src/main/resources/data/job-offer-applications.json
  skillful_network_server/src/main/resources/data/job-offers.json
  skillful_network_server/src/main/resources/data/training-applications.json
  skillful_network_server/src/main/resources/data/trainings.json
  skillful_network_server/src/main/resources/data/users.json
  skillful_network_server/src/test/java/fr/uca/cdr/skillful_network/generator/JSONGenerator.java
Labels: back, code, test

#65 1.4.2-pf-feat update list-user with follow feature
  skillful_network_client/src/app/home/lists/users-list/users-list.component.ts
  skillful_network_client/src/app/shared/components/list/list.component.html
  skillful_network_client/src/app/shared/components/list/list.component.ts
  skillful_network_client/src/styles.scss
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/user/UserController.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/impl/user/FollowStateTrackerServiceImpl.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/impl/user/UserServiceImpl.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/user/UserService.java
  skillful_network_server/src/test/java/fr/uca/cdr/skillful_network/services/user/UserServiceTest.java
Labels: code, front

#57 1.5 (sh) feat : Add unit test for FollowStateTrackerServiceImpl.getFS…
  skillful_network_server/src/test/java/fr/uca/cdr/skillful_network/services/user/FollowStateTrackerServiceTest.java
Labels: back, code, test

#72 1.4.8-pf-feat-follow integrate notification mgt with Post creation update and delete
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/post/PostController.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/controller/user/FollowStateTrackerController.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/entities/user/FollowStateTracker.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/entities/user/Notification.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/repositories/user/NotificationRepository.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/impl/post/PostServiceImpl.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/impl/user/FollowStateTrackerServiceImpl.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/post/PostService.java
  skillful_network_server/src/main/java/fr/uca/cdr/skillful_network/services/user/FollowStateTrackerService.java
  skillful_network_server/src/test/java/fr/uca/cdr/skillful_network/services/post/PostServiceTest.java
Labels: back, code
